name: Continuous-Integration

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      working-directory: azure_function
      run: npm install

    - name: Run tests
      working-directory: azure_function
      run: npm test

    - name: Update Coverage Badge
      # GitHub actions: default branch variable
      # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
      # if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      uses: we-cli/coverage-badge-action@main

  terraform_checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Terraform Format Check
      run: |
        cd terraform
        terraform init -backend=false -input=false
        terraform fmt -check -recursive
    
    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate

    # - name: Test with Checkov
    #   id: checkov
    #   uses: bridgecrewio/checkov-action@master
    #   with:
    #     directory: terraform
    #     framework: terraform 
