name: Continuous-Integration

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      working-directory: azure_function
      run: npm install

    - name: Run tests
      working-directory: azure_function
      run: npm test
    
    - uses: codecov/codecov-action@v3
      with:
        directory: azure_function
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Lint Code Base
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_JAVASCRIPT_ES: true
        VALIDATE_PYTHON_BLACK: true
        VALIDATE_HTML: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  terraform_checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.5  # or the version you want

    - name: Terraform Format Check
      run: |
        cd terraform
        terraform init -backend=false -input=false
        terraform fmt -check -recursive
    
    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate

    # - name: Test with Checkov
    #   id: checkov
    #   uses: bridgecrewio/checkov-action@master
    #   with:
    #     directory: terraform
    #     framework: terraform
    #     skip_check: CKV_AZURE_225,CKV_AZURE_212,CKV_AZURE_206,CKV_AZURE_33,CKV2_AZURE_38,CKV2_AZURE_21,CKV2_AZURE_1,CKV2_AZURE_33,CKV_AZURE_221,CKV2_AZURE_41,CKV2_AZURE_40
